project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

metadata-files:
  - _metadata.yml

website:
  title: "Runze Tai"
  navbar:
    left:
      - text: Personal CV
        file: cv.qmd
      - text: Research
        file: research.qmd
      - text: Blog
        file: blog.qmd
    right:
      - icon: github
        href: https://github.com/Tommy-Ty
      - icon: threads
        href: https://threads.net/@ta1m0u
      - icon: sina-weibo
        href: https://weibo.com/u/2821436162  
  back-to-top-navigation: true
  page-footer: "© Runze Tai 2025, powered by [![](quarto.png){height=12pt}](https://quarto.org)."
  reader-mode: true


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header: _includes/head.html

publish:
  provider: github
  repo: Tommy-Ty/personal-website