---
title: "Research"
format:
  html:
    css: styles.css
---

*(This page is under construction.)*

## PUBLICATIONS & MANUSCRIPS

### Publications

- Gao, Qiqi, and **Runze Tai** (2025), "Political Nonsteady-State Based on World Simulation: Sora’s Intelligent Video Generation and History Remodelling," *Journal of Xinjiang Normal University (Edition of Philosophy and Social Sciences)* 46*(2) *[in Chinese]*. *CSSCI*  

### Conference Paper Presentations

- Yang, Duancheng, and **Runze Tai**, "The Eve of Leviathan's Birth: Bureucratic Reforms and State Building in Medieval China," *American Political Science Association (APSA) Annual Meeting,* November 2025 (expected) [equal contribution, co-first author].

- Yang, Duancheng, Dehao Zhao and **Runze Tai**, "Power Struggles, Credible Commitments, and State Building in Medieval China," *Midwest Political Science Association (MPSA) Annual Meeting,* April 2025 [corresponding author].

- **Tai, Runze**, "Imperial Infrastructure and State Building: Evidence from Stages in Ming China (1522-1620)," *The Sixth Academic Workshop on "State and Governance in History" (hosted by RUC & ECUPL),* November 2024.

- Jia, Xiaoteng and **Runze Tai**, "Can State Governance Capacity Ensure Public Health Security? An Empirical Study Based on World Governance Index and COVID-19 Vaccination Rate in Four Southeast Asian Countries," *The First Chinese Undergraduate Seminar on Political Science (hosted by SCNU)*, November 2021. * *First Prize Paper in the Seminar Achievement Selection*


### Database

- Yang, Duancheng and **Runze Tai**. *Political Elite Database of Wei During the Three Kingdoms Period.*


## RESEARCH EXPERIENCE

### Research Assistant | 2025.6-2025.8 (expected)

Xingchen Lan, PhD. Student, Wilf Family Department of Politics, New York University

*Assisted in data collection.*

***

### Research Assistant, Political Science Institute, ECUPL | 2022.9-2025.6

- **Key Programme of National Social Science Foundation of China** 

&emsp; “Research on the Political Guarantee of Accelerating Digital Development and Building a Digital China” (Programme No. 21AZD021), Programme Director: Prof. Gao Qiqi. | 2022.9-2024.6

&emsp; *Participated in the research of the part named “Technological Governance of Artificial Intelligence and its Political Guarantees” in the program and produced a journal article as an interim outcome. Participated in proofreading, literature collection and collation. Participated in writing and collation of the final report of the programme.* 

***

- **General Programme of National Social Science Foundation of China** 

&emsp; “Research on the Mechanism of Governments Promoting Entrepreneurship Cultivation in the New Era” (Programme No. 18BZZ087), Programme Director: Associate Prof. Zhang Xianli. | 2022.9-2023.6

&emsp; *Participated in the field research of the programme, conducting interviews with local government officials to collect first-hand information and data. Participated in the part named “Local Government and Entrepreneurship” of the programme, and was mainly responsible for the empirical part of the programme, including data collection and collation, research design, hypothesis testing, robustness testing and heterogeneity analysis. Some responsibilities including proofreading and collation.*

***

- The Coordination Mechanism Programme 2024 for International Communication Capacity Building Research of the Foreign Languages Bureau of China

&emsp; “Problems and Countermeasures to Enhance the Influence of Chinese Civilisation’s Communicating Power”, Programme Director: Associate Prof. Zhang Xianli.  | 2024.6-2023.12

&emsp; *Participated in the writing of a comprehensive research report on the project with a special report as an interim outcome.*

***

- “Global Governance Index 2024” 

&emsp; --- a joint programme between the Foreign Languages Bureau of China and East China University of Political Science and Law, Chief Expert: Prof. Gao Qiqi; Programme Director: Associate Prof. Yan Xingjian. | 2022.9-2022.12

&emsp; *The project measures and evaluates the participation and contribution of 189 countries to global governance over the past 10 years through objective data. I was involved in the collection of information and data for the project, as well as in the writing of the Global Governance Index 2022 Report.*

***

- “Index of International Security Situation Awareness,IISSA (2023)”

&emsp; --- a joint programme between University of International Relations and East China University of Political Science and Law, Chief Expert: Prof. Tan Xiuying, and Prof. Gao Qiqi; Programme Director: Associate Prof. Yan Xingjian. | 2022.9-2022.12

&emsp; *This project assessed the security situation of 82 target countries in 2023, with the goal of building a refined security situational awareness model to predict security threats in real time. The project report was invited as an official recommended publication to be presented at the 11th Beijing Xiangshan Forum 2024. I was involved in the information collection and data collation of the project.*

## Theses

- "State Capacity and the Implementation of Hedging Strategy: An Empirical Analysis Based on Countries in Southeast Asia,"  Bachelor's Thesis, Sichuan International Studies University, 2022 *(\* 2022 Distinguished Thesis Award of Chongqing Municipality)*.

- "The Information Function and State Building of the Imperium: A Political Economic Analysis on Administrative Capacity of China in Ming Dynasty," Master's Thesis, East China University of Political Science and Law, 2025.

