---
########
format: pdf
documentclass: article


########
header-includes: 
  - \usepackage{fontenc}
  #- \usepackage[UTF8]{ctex} 
  - \usepackage{xeCJK}
  - \usepackage{hyperref}
  - \usepackage[a4paper,margin=1in]{geometry}
  - \usepackage{multicol}

mainfont: EB Garamond
mathspec: true
---
<!-- TITLE -->
\begin{huge}\begin{center}{Runze Tai}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center} \href{mailto:rztai25@m.fudan.edu.cn}{\texttt{rztai25@m.fudan.edu.cn}} \\
School of International Relations and Public Affairs, Fudan University, 220 Handan Rd., Shanghai 200433, China
\end{center}
\vspace{15pt}

## EDUCATION
\hrule

**\quad Fudan University**,
School of International Realations and Public Affairs (SIRPA)  **\hfill from 2025.9**

- Ph.D. candidate in political science (specializing in Chinese politics)
- Supervisor: Prof. He Donghang

***

**\quad East China University of Political Science and Law**,
School of Government  **\hfill 2022.9-2025.6**

- LL.M. in comparative politics
- Supervisor: Prof. Gao Qiqi
- Thesis: *The Threads of Governance: Informational Function and State Building in Ming China*

***

**\quad Sichuan International Studies University**, School of International Relations **\hfill 2018.9-2022.6**

- LL.B. in international politics
- Tutor: Dr. Tang Yu
- Thesis: *State Capacity and the Implementation of Hedging Strategy: An Empirical Analysis Based on Countries in Southeast Asia*


## RESEARCH INTERESTS
\hrule
\begin{multicols}{2}
\quad \textbf{Fields}
\begin{itemize}
\setlength{\parskip}{0pt}
\item Historical political economy 
\item Comparative politics
\item Historical sociology
\item New institutional economics
\item Social science methodology
\end{itemize}

\quad \textbf{Interests}
\begin{itemize}
\setlength{\parskip}{0pt}
\item State capacity \& State building
\item Authoritarianism
\item Conflicts and wars
\item Quantitative methods and machine learning in social science
\end{itemize}
\end{multicols}

## PUBLICATIONS & MANUSCRIPS
\hrule
**\quad Publications**

- Gao, Qiqi, and **Runze Tai** (2025), "Political Nonsteady-State Based on World Simulation: Sora’s Intelligent Video Generation and History Remodelling," *Journal of Xinjiang Normal University (Edition of Philosophy and Social Sciences)* [*新疆师范大学学报(哲学社会科学版)*] *46*(2).
\hfill **CSSCI*  

**\quad Conference Paper Presentations**

- Yang, Duancheng, and **Runze Tai**, "The Eve of Leviathan's Birth: Bureucratic Reforms and State Building in Medieval China," *American Political Science Association (APSA) Annual Meeting,* November 2025 (expected) [equal contribution, co-first author].

- Yang, Duancheng, Dehao Zhao and **Runze Tai**, "The Failure of Leviathan: Power Struggles, Credible Commitments, and State Building in Medieval China," *Midwest Political Science Association (MPSA) Annual Meeting,* April 2025 [corresponding author].

- **Tai, Runze**, "Imperial Infrastructure and State Building: Evidence from Stages in Ming China (1522-1620)," *The Sixth Academic Workshop on "State and Governance in History" (hosted by RUC & ECUPL),* November 2024.

- Jia, Xiaoteng and **Runze Tai**, "Can State Governance Capacity Ensure Public Health Security? An Empirical Study Based on World Governance Index and COVID-19 Vaccination Rate in Four Southeast Asian Countries," *The First Chinese Undergraduate Seminar on Political Science (hosted by SCNU)*, November 2021 [corresponding author].
\hfill **First Prize Paper in the Seminar Achievement Selection*


**\quad Database**

- Yang, Duancheng and **Runze Tai**. *Political Elite Database of Wei During the Three Kingdoms Period.*


## RESEARCH EXPERIENCE
\hrule

**\quad Research Assistant \hfill 2025.9-**

- Fudan Data Intelligence and Social Computing Lab (Fudan-DISC)

    *Data annotation.*

**\quad Research Assistant \hfill 2025.6-2025.8**

- Xingchen Lan, PhD. Student, Wilf Family Department of Politics, New York University

    *Assisted in data collection.*


**\quad Research Assistant, Political Science Institute, ECUPL \hfill 2022.9-2025.6**

- **Key Programme of National Social Science Foundation of China** --“Research on the Political Guarantee of Accelerating Digital Development and Building a Digital China” (Programme No. 21AZD021), Programme Director: Prof. Gao Qiqi.
\hfill 2022.9-2024.6

    *Participated in the research of the part named “Technological Governance of Artificial Intelligence and its Political Guarantees” in the program and produced a journal article as an interim outcome. Participated in proofreading, literature collection and collation. Participated in writing and collation of the final report of the programme.* 

***

- **General Programme of National Social Science Foundation of China** --“Research on the Mechanism of Governments Promoting Entrepreneurship Cultivation in the New Era” (Programme No. 18BZZ087), Programme Director: Associate Prof. Zhang Xianli.
\hfill 2022.9-2023.6

    *Participated in the field research of the programme, conducting interviews with local government officials to collect first-hand information and data. Participated in the part named “Local Government and Entrepreneurship” of the programme, and was mainly responsible for the empirical part of the programme, including data collection and collation, research design, hypothesis testing, robustness testing and heterogeneity analysis. Some responsibilities including proofreading and collation.*

***

- The Coordination Mechanism Programme 2024 for International Communication Capacity Building Research of the Foreign Languages Bureau of China --“Problems and Countermeasures to Enhance the Influence of Chinese Civilisation’s Communicating Power”, Programme Director: Associate Prof. Zhang Xianli.
\hfill 2024.6-2023.12

    *Participated in the writing of a comprehensive research report on the project with a special report as an interim outcome.*

***

- “Global Governance Index 2024” --a joint programme between the Foreign Languages Bureau of China and East China University of Political Science and Law, Chief Expert: Prof. Gao Qiqi; Programme Director: Associate Prof. Yan Xingjian.
\hfill 2022.9-2022.12

    *The project measures and evaluates the participation and contribution of 189 countries to global governance over the past 10 years through objective data. I was involved in the collection of information and data for the project, as well as in the writing of the Global Governance Index 2022 Report.*

***

- “Index of International Security Situation Awareness,IISSA (2023)”, --a joint programme between University of International Relations and East China University of Political Science and Law, Chief Expert: Prof. Tan Xiuying, and Prof. Gao Qiqi; Programme Director: Associate Prof. Yan Xingjian.
\hfill 2022.9-2022.12

    *This project assessed the security situation of 82 target countries in 2023, with the goal of building a refined security situational awareness model to predict security threats in real time. The project report was invited as an official recommended publication to be presented at the 11th Beijing Xiangshan Forum 2024. I was involved in the information collection and data collation of the project.*
\


## TEACHING EXPERIENCE
\hrule
**\quad Teaching Assistant, SIRPA, Fudan \hfill 2025.9-2026.1 (expected)**

- Course: Artificial Intelligence and Social Science Research (2025 Fall)

    *Some responsibilities including grading and answering students' questions.*

**\quad Teaching Assistant, School of Government, ECUPL \hfill 2023.2-2023.6**

- Course: Intro to Insurance Studies (2023 Spring)

    *Some responsibilities including leading discussions sections, recording attendance, collecting assignments, and grading exams for undergraduate courses.*

## SERVICE
\hrule

- Content Manager, WeChat Public Platform, Research Center of Chinese Path to Modernization, IAS-Fudan \hfill 2025.5 to present
    
    *Responsible for content curation, editing, and publishing of academic outreach materials for a research-oriented WeChat platform. Collaborate with researchers to translate scholarly output into accessible public content, enhancing the center’s public engagement and visibility.*

- Student Affairs, Student Union, School of International Relations, SISU \hfill 2018.10-2021.6

    *Planned and organized student events and activities such as annual galas engaging hundreds of participants. Coordinated logistics, communications, and on-site execution for extracurricular programming aimed at enhancing student life.*

## SCHOLARSHIPS & AWARDS
\hrule
- Postgraduate Scholarships, ECUPL \hfill 2022-2024
- Outstanding Thesis, Chongqing Municipality \hfill 2022
- Outstanding Thesis, SISU \hfill 2022
- Outstanding Graduate, SISU \hfill 2022
- Excellent Student Cadre, SISU \hfill 2021
- Excellent Student, SISU \hfill 2020
- Excellent Student Scholarships, SISU \hfill 2019-2022


## LANGUAGE & COMPUTER SKILLS
\hrule

\begin{multicols}{2}

\quad \textbf{Language}
\begin{itemize}
\setlength{\parskip}{0pt}
\item Chinese (native)
\item English
    \begin{itemize}
    \setlength{\parskip}{0pt}
    \item TEM-8: Good
    \item TEM-4: Good
    \item TOFEL: pending
    \end{itemize}
\end{itemize}

\

\quad \textbf{Computer}
\begin{itemize}
\setlength{\parskip}{0pt}
\item \textbf{R}
\item \textbf{Quarto}
\item \textbf{ArcGIS}
\item \LaTeX
\item STATA
\item Python
\item SQL
\end{itemize}

\end{multicols}

## REFERENCES
\hrule
\begin{multicols}{2}
\textbf{Qiqi Gao}\\
Professor\\
School of International Relations and Public Affairs, FDU\\
Email: \texttt{gaoqiqilove@163.com}\\

\

\textbf{Haibing Yan}\\
Associate Professor\\
School of Government, ECUPL\\
Email: \texttt{2183@ecupl.edu.cn}\\

\end{multicols}